CREATE TABLE IF NOT EXISTS common_passwords (
    password TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS "2401499" (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
